<?php $title='Contact & infos pratiques — CS Godbrange'; include 'partials/header.php'; ?>
<section class="contact-hero"><div><span class="eyebrow">NOUS TROUVER & NOUS CONTACTER</span><h1>CONTACT &<br><em>INFOS PRATIQUES</em></h1><p>Une question sur les inscriptions, les entraînements ou la vie du club ? Retrouvez ici toutes les informations utiles.</p></div></section>

<section class="section contact-cards"><article><div><h3>STADE MUNICIPAL</h3><p class="contact-detail"><span aria-hidden="true">⌖</span><span>Rue Jean Moulin<br>54590 Hussigny-Godbrange</span></p></div></article><article><div><h3>NOUS ÉCRIRE</h3><p class="contact-detail"><span aria-hidden="true">✉</span><span>godbrangehussignycs@gmail.com</span></p></div></article><article><div><h3>NOUS APPELER</h3><p class="contact-detail"><span aria-hidden="true">☎</span><span>03 82 44 36 87<br>Du lundi au vendredi</span></p></div></article><article class="social-card"><div><h3>RÉSEAUX SOCIAUX</h3><p><a href="#" aria-label="Facebook du CS Godbrange"><svg class="official-social-icon facebook-logo" viewBox="0 0 24 24" aria-hidden="true"><path d="M24 12.073C24 5.405 18.627 0 12 0S0 5.405 0 12.073C0 18.099 4.388 23.094 10.125 24v-8.437H7.078v-3.49h3.047V9.414c0-3.025 1.792-4.697 4.533-4.697 1.313 0 2.686.236 2.686.236v2.974h-1.513c-1.49 0-1.956.931-1.956 1.887v2.259h3.328l-.532 3.49h-2.796V24C19.612 23.094 24 18.099 24 12.073Z"/></svg><span>Facebook</span></a><a href="#" aria-label="Instagram du CS Godbrange"><svg class="official-social-icon instagram-logo" viewBox="0 0 24 24" aria-hidden="true"><path d="M7.75 2h8.5A5.76 5.76 0 0 1 22 7.75v8.5A5.76 5.76 0 0 1 16.25 22h-8.5A5.76 5.76 0 0 1 2 16.25v-8.5A5.76 5.76 0 0 1 7.75 2Zm0 2A3.75 3.75 0 0 0 4 7.75v8.5A3.75 3.75 0 0 0 7.75 20h8.5A3.75 3.75 0 0 0 20 16.25v-8.5A3.75 3.75 0 0 0 16.25 4h-8.5ZM17 5.5A1.5 1.5 0 1 1 17 8a1.5 1.5 0 0 1 0-2.5ZM12 7a5 5 0 1 1 0 10 5 5 0 0 1 0-10Zm0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z"/></svg><span>Instagram</span></a></p></div></article></section>

<section class="section contact-main"><div class="contact-form-wrap"><span class="eyebrow">UNE QUESTION ?</span><h2>CONTACTEZ LE CLUB</h2><p>Ce formulaire est présenté pour la démonstration du site. Aucun message ne sera envoyé.</p><form class="contact-form" onsubmit="return false"><div class="form-row"><label>PRÉNOM<input type="text" placeholder="Votre prénom"></label><label>NOM<input type="text" placeholder="Votre nom"></label></div><label>ADRESSE E-MAIL<input type="email" placeholder="vous@exemple.fr"></label><label>OBJET<select><option>Choisissez un sujet</option><option>Inscription / Licence</option><option>Horaires d’entraînement</option><option>Partenariat</option><option>Bénévolat</option><option>Autre demande</option></select></label><label>MESSAGE<textarea rows="6" placeholder="Écrivez votre message..."></textarea></label><label class="form-consent"><input type="checkbox"> J’accepte que mes informations soient utilisées pour répondre à ma demande.</label><button class="btn" type="button">ENVOYER LE MESSAGE →</button><small>FORMULAIRE DE DÉMONSTRATION — AUCUNE DONNÉE N’EST TRANSMISE</small></form></div>
<aside class="contact-aside"><div class="map-card"><a class="map-preview" href="https://www.google.com/maps/search/?api=1&query=Rue+Jean+Moulin%2C+54590+Hussigny-Godbrange" target="_blank" rel="noopener" aria-label="Ouvrir l’emplacement du stade dans Google Maps"><img src="assets/images/stade-map.svg" alt="Plan indiquant le Stade Municipal, rue Jean Moulin à Hussigny-Godbrange"></a><a href="https://www.google.com/maps/search/?api=1&query=Rue+Jean+Moulin%2C+54590+Hussigny-Godbrange" target="_blank" rel="noopener">OUVRIR DANS GOOGLE MAPS ↗</a></div><div class="club-hours"><span class="eyebrow">ACCUEIL DU CLUB</span><h3>PERMANENCES</h3><p><b>MERCREDI</b><span>18h30 — 20h00</span></p><p><b>SAMEDI</b><span>10h00 — 12h00</span></p><small>Hors jours fériés et vacances scolaires.</small></div></aside></section>

<section class="training-section"><div class="section"><div class="training-title"><div><span class="eyebrow">SAISON 2024–2025</span><h2>HORAIRES DES ENTRAÎNEMENTS</h2></div><p>Les horaires peuvent évoluer selon les périodes et les compétitions. Contactez l’éducateur de la catégorie avant votre première séance.</p></div><div class="training-grid"><article><span>U7 – U9</span><h3>ÉCOLE DE FOOT</h3><p><b>MERCREDI</b>14h00 — 15h30</p><p><b>SAMEDI</b>10h00 — 11h30</p><small>Terrain synthétique</small></article><article><span>U11 – U13</span><h3>PRÉFORMATION</h3><p><b>MERCREDI</b>16h00 — 17h30</p><p><b>VENDREDI</b>17h30 — 19h00</p><small>Terrain synthétique</small></article><article><span>U15 – U18</span><h3>FORMATION</h3><p><b>MERCREDI</b>18h00 — 19h30</p><p><b>VENDREDI</b>18h30 — 20h00</p><small>Terrain principal</small></article><article><span>SENIORS</span><h3>PÔLE COMPÉTITION</h3><p><b>MARDI</b>19h30 — 21h15</p><p><b>JEUDI</b>19h30 — 21h15</p><small>Terrain principal</small></article><article><span>VÉTÉRANS</span><h3>+ 35 ANS</h3><p><b>VENDREDI</b>19h30 — 21h00</p><p><b>DIMANCHE</b>Selon calendrier</p><small>Terrain principal</small></article><article><span>GARDIENS</span><h3>SPÉCIFIQUE</h3><p><b>MERCREDI</b>17h30 — 18h30</p><p><b>JEUDI</b>18h30 — 19h30</p><small>Sur convocation</small></article></div></div></section>

<section class="section practical-grid"><div><span class="eyebrow">VENIR AU STADE</span><h2>ACCÈS & ÉQUIPEMENTS</h2><div class="practical-list"><article><b>01</b><div><h3>STATIONNEMENT</h3><p>Parking gratuit à proximité immédiate du stade. Places réservées aux personnes à mobilité réduite.</p></div></article><article><b>02</b><div><h3>VESTIAIRES & CLUB-HOUSE</h3><p>Vestiaires joueurs et arbitres, douches, buvette et espace de convivialité les jours de match.</p></div></article><article><b>03</b><div><h3>ACCÈS SUPPORTERS</h3><p>Ouverture du stade 45 minutes avant le coup d’envoi. Entrée principale rue Jean Moulin.</p></div></article></div></div><aside class="documents-box"><h3>DOCUMENTS UTILES</h3><a href="#">DOSSIER D’INSCRIPTION 2024–2025 <span>↓</span></a><a href="#">RÈGLEMENT INTÉRIEUR DU CLUB <span>↓</span></a><a href="#">AUTORISATION PARENTALE <span>↓</span></a><a href="#">CHARTE DU JOUEUR <span>↓</span></a></aside></section>
<?php include 'partials/footer.php'; ?>
