<?php $title='Nos partenaires — CS Godbrange'; include 'partials/header.php'; ?>
<section class="partners-hero"><div><span class="eyebrow">ILS FONT VIVRE LE CLUB</span><h1>NOS<br><em>PARTENAIRES</em></h1><p>Le C.S. Godbrange remercie l’ensemble des entreprises, institutions et acteurs locaux qui nous accompagnent tout au long de la saison.</p></div></section>

<section class="section partners-intro"><div><span class="eyebrow">UN ENGAGEMENT COMMUN</span><h2>ENSEMBLE POUR LE FOOTBALL LOCAL</h2></div><p>Grâce à leur fidélité, nos partenaires participent à la formation des jeunes, à l’équipement de nos équipes et à l’organisation des événements du club. Chaque soutien compte et contribue directement au développement du CSG.</p></section>

<section class="section partner-level major-level"><div class="partner-level-title"><div><span class="eyebrow">PARTENAIRES MAJEURS</span><h2>AU CŒUR DU PROJET</h2></div><p>Ils accompagnent le club dans ses projets structurants et sur l’ensemble de la saison.</p></div><div class="major-partners"><article><div class="partner-logo city-logo"><b>VILLE</b><strong>HUSSIGNY-<br>GODBRANGE</strong></div><h3>VILLE D’HUSSIGNY-GODBRANGE</h3><p>Partenaire institutionnel principal</p></article><article><div class="partner-logo distrib-logo"><b>DISTRIB</b><strong>54</strong></div><h3>DISTRIB 54</h3><p>Partenaire équipement & logistique</p></article><article><div class="partner-logo inter-logo"><strong>INTERSPORT</strong><small>LONGWY</small></div><h3>INTERSPORT LONGWY</h3><p>Équipementier officiel du club</p></article></div></section>

<section class="official-partners"><div class="section partner-level"><div class="partner-level-title"><div><span class="eyebrow">PARTENAIRES OFFICIELS</span><h2>À NOS CÔTÉS TOUTE L’ANNÉE</h2></div><p>Des entreprises engagées qui partagent nos valeurs de proximité, de passion et de transmission.</p></div><div class="official-grid"><article><div class="partner-logo"><strong>SCIÈRERIEVO</strong><small>BOIS & CONSTRUCTION</small></div><h3>SCIÈRERIEVO</h3></article><article><div class="partner-logo"><strong>GARAGE<br>MARTIN</strong><small>AUTOMOBILE</small></div><h3>GARAGE MARTIN</h3></article><article><div class="partner-logo"><strong>BATI 54</strong><small>CONSTRUCTION</small></div><h3>BATI 54</h3></article><article><div class="partner-logo"><strong>LE STADIUM</strong><small>BAR • RESTAURANT</small></div><h3>LE STADIUM</h3></article><article><div class="partner-logo"><strong>AXA</strong><small>ASSURANCES</small></div><h3>AXA LONGWY</h3></article><article><div class="partner-logo"><strong>FRESH<br>MARKET</strong><small>ALIMENTATION</small></div><h3>FRESH MARKET</h3></article></div></div></section>

<section class="section partner-level local-level"><div class="partner-level-title"><div><span class="eyebrow">RÉSEAU LOCAL</span><h2>PARTENAIRES DE PROXIMITÉ</h2></div><p>Commerçants, artisans et indépendants : leur présence fait la force du tissu économique local.</p></div><div class="local-grid"><article><div class="partner-logo"><strong>BOULANGERIE<br>DU CENTRE</strong></div><h3>BOULANGERIE DU CENTRE</h3></article><article><div class="partner-logo"><strong>PHARMACIE<br>DES SPORTS</strong></div><h3>PHARMACIE DES SPORTS</h3></article><article><div class="partner-logo"><strong>ÉLEC<br>SERVICES</strong></div><h3>ÉLEC SERVICES</h3></article><article><div class="partner-logo"><strong>TRANS<br>LORRAINE</strong></div><h3>TRANS LORRAINE</h3></article><article><div class="partner-logo"><strong>IMMO<br>CONSEIL</strong></div><h3>IMMO CONSEIL</h3></article><article><div class="partner-logo"><strong>CAFÉ DE<br>LA PLACE</strong></div><h3>CAFÉ DE LA PLACE</h3></article><article><div class="partner-logo"><strong>JARDINS<br>VERTS</strong></div><h3>JARDINS VERTS</h3></article><article><div class="partner-logo"><strong>OPTIC<br>PLUS</strong></div><h3>OPTIC PLUS</h3></article></div></section>

<section class="partner-cta"><div><span class="eyebrow">REJOIGNEZ L’AVENTURE</span><h2>DEVENEZ PARTENAIRE DU CSG</h2><p>Associez votre image à un club familial, dynamique et engagé dans son territoire. Nous construisons des offres adaptées à chaque entreprise, quelle que soit sa taille.</p><a class="btn" href="contact.php">ÉCHANGER AVEC LE CLUB →</a></div><div class="partner-benefits"><article><b>01</b><h3>VISIBILITÉ LOCALE</h3><p>Présence au stade, sur nos supports et nos réseaux.</p></article><article><b>02</b><h3>RÉSEAU & CONVIVIALITÉ</h3><p>Rencontres avec les acteurs économiques du territoire.</p></article><article><b>03</b><h3>IMPACT POSITIF</h3><p>Soutenez la formation et le sport amateur local.</p></article></div></section>
<?php include 'partials/footer.php'; ?>
